- name: Generate configuration file
  template:
    src: docklet.conf.j2
    dest: "{{ docklet_work_dir }}/conf/docklet.conf"

- name: Init docklet master, web
  command: "{{ docklet_work_dir }}/bin/docklet-master init"
